export const catTexts = [
    "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
    "The color of the points in Siamese cats is heat related. Cool areas are darker.",
    "Every time you masturbate God kills a kitten. Please, think of the kittens.",
    "Female cats are \"polyestrous,\" which means they may have many heat periods over the course of a year. A heat period lasts about 4 to 7 days if the female is bred; if she is not, the heat period lasts longer and recurs at regular intervals.",
    "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
    "On average, a cat will sleep for 16 hours a day.",
    "Ancient Egyptian family members shaved their eyebrows in mourning when the family cat died.",
    "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees, and can turn in the direction of sound 10 times faster than those of the best watchdog.",
    "Mature cats with no health problems are in deep sleep 15 percent of their lives. They are in light sleep 50 percent of the time. That leaves just 35 percent awake time, or roughly 6-8 hours a day.",
    "Cheetahs do not roar, as the other big cats do. Instead, they purr.",
    "Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often, especially when they are excited.",
    "All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.",
    "In the wild, lions live for an average of 12 years and up to 16 years. They live up to 25 years in captivity.",
    "A cat has more bones than a human; humans have 206, but the cat has 230 (some cites list 245 bones, and state that bones may fuse together as the cat ages).",
    "Among many other diseases, cats can suffer from anorexia, senility, feline AIDS and acne.",
    "Recent studies have shown that cats can see blue and green. There is disagreement as to whether they can see red.",
    "The cat has 500 skeletal muscles (humans have 650).",
    "Why do people have cats? One survey that looked into the reasons people have cats found the following: companionship/comfort 27%, stress/blood pressure relief --22%, something to love/feel neededâ 9%, lifts depression/boosts moods 10%, subject of communication/stimulates interest 8%.",
    "The female cat reaches sexual maturity at around 6 to 10 months and the male cat between 9 and 12 months.",
    "Cats come back to full alertness from the sleep state faster than any other creature.",
    "Purring does not always indicate that a cat is happy. Cats will also purr loudly when they are distressed or in pain.",
    "A female cat will be pregnant for approximately 9 weeks or between 62 and 65 days from conception to delivery.",
    "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees, and can turn in the direction of sound 10 times faster than those of the best watchdog.",
    "Cats, just like people, are subject to asthma. Dust, smoke, and other forms of air pullution in your cat's environment can be troublesome sources of irritation.",
    "In 1987 cats overtook dogs as the number one pet in America."
];
